name: "Build Android debug APK when push to QA Branch"
branding:
  icon: "package"
  color: "red"
description: "Build Android debug APK and upload as a github release match the created new tag"
author: "AbdullahAlaradi"
inputs:
  GITHUB_TOKEN:
    description: "Github secret token to allow automated publishing of APK to release."
runs:
  using: "docker"
  image: "Dockerfile"
